name: rl_foc
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7.5
  - pip=19.3.1
  - numpy=1.17.4
  - pandas=0.25.1
  - matplotlib=3.1.1
  - pytorch=1.3.1
  - torchvision=0.4.2
  - cpuonly=1.0
  - tqdm=4.40.0
  - h5py=2.9.0
  - pip:
    - pyqt5==5.13.2
    - gym==0.15.4
    - pyyaml==5.2
